### ISSUE TITLE
Spring starting issue (in tomcat container)

### ISSUE THREAD

**Issue by fliot** [bazhenov/groovy-shell-server#13]
Hi,

I inserted this:
```xml
    <bean class="me.bazhenov.groovysh.spring.GroovyShellServiceBean">
        <property name="socket" value="6789" />
        <property name="launchAtStart" value="${groovy.console.enabled}" />
        <property name="publishContextBeans" value="true" />
        <property name="bindings-ref" value="bindings" />
    </bean>
```

And I have issue on startup :

```
2015-08-31 19:19:40,884 [ost-startStop-1] ERROR ContextLoader                  - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'me.bazhenov.groovysh.spring.GroovyShellServiceBean#0' defined in class path resource [META-INF/spring/popproduction-war.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'socket' of bean class [me.bazhenov.groovysh.spring.GroovyShellServiceBean]: Bean property 'socket' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1361)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1086)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:192)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:585)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:282)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:204)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1073)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'socket' of bean class [me.bazhenov.groovysh.spring.GroovyShellServiceBean]: Bean property 'socket' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:1052)
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:921)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:76)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:58)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1358)
	... 26 more
```
Any input will be appreciated,

Thanks in advance,

Francois

**Comment by grzechol** [comment]
Hi Francois,

The exception message is very accurate: you are trying to set property "socket" which doesn't exist. Please take a look at the source code: if you open GroovyShellServiceBean.java, you will see there's no property "socket", nor "setSocket" method.

Maybe you want to set the "port" property?

Regards,
Grzegorz

**Comment by fliot** [comment]
Right indeed...
Thanks for the answer, and sorry for disturbing.
Regards.
